### ISSUE TITLE
list collaboration menu item missing

### ISSUE THREAD

**Issue by rbaertsch** [UCSC-MedBook/MedBook-Telescope3#11]
on v125

**Comment by e-t-k** [comment]
"List Collaborations" menu item no longer missing in cloud-hosting branch. Don't know when it reappeared.

![screen shot 2016-05-24 at 3 57 35 pm](https://cloud.githubusercontent.com/assets/19291809/15522581/55c60fee-21c8-11e6-89df-ff8c8c43224a.png)
